### ISSUE TITLE
Add Database Schema

### ISSUE THREAD

**Issue by nick-andren** [cybergrunge-ops/cybergrungewebsite#7]
I realize that [the main Readme has a Database section](https://github.com/cybergrunge-ops/cybergrungewebsite#database) that details some of the schema, though it might be easier to include the schema somewhere in the repo itself. We could generate a .sql file with the `CREATE DATABASE` statements either by running `SHOW CREATE TABLE [tablename]` on each table or by going off of the description in the Readme

**Comment by cybergrunge-ops** [comment]
i do think before that a better schema needs to be made up just so things are organized better.

i kind of dont want to add another table but it seems like it would just be nicer to have a separate table for album styles, for instance. that and i'm not sure how to validate ownership yet which especially is hard to merge with existing website since a ton of albums don't have any metadata at all and i am not sure how to go about adding them. idk. im gonna open a bunch of other issues

**Comment by nick-andren** [comment]
After the initial schema is set, we can add some migrations to make changes to the database if needed. One of the migrations could be adding the table for albums, but have it so that there's a migration for adding existing albums to it at the same time (maybe with a one-off script or something, just to import the data). Just an idea

**Comment by nick-andren** [comment]
Resolved as of [commit `cbb8a1e`](https://github.com/cybergrunge-ops/cybergrungewebsite/commit/cbb8a1ec28079d76a8bc94dc3cc34fd792790295)
